[book]
title = "Bevy Advanced Item System"
authors = ["Andre Roelofs"]
language = "en"
src = "src"

[output.html]
default-theme = "frappe"
preferred-dark-theme = "frappe"
additional-css = ["theme/catppuccin.css", "theme/inline-code.css"]
site-url = "/bevy_advanced_item_system/"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
